"""create depenses table

Revision ID: 6c19cd0de3bb
Revises: e6c7a7b50fb8
Create Date: 2026-09-08 16:40:56.058794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c19cd0de3bb'
down_revision: Union[str, Sequence[str], None] = 'e6c7a7b50fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
